### ISSUE TITLE
Set % in regulator mode Z-wave termostat 4512757

### ISSUE THREAD

**Issue by tj75** [NamronAS/Namron_Homey#149]
I have 3 new z-wave thermostats recommended and installed from Spoton/Elektroimportøren to use with Homey on heating cables where I have no sensors. 

But without flow cards to set %, the "smartness" is almost zero.

Please add card to set regulator %. 🙏🙏
This is the core function on apps like this when the thermostats are mounted outside the room and don't have floor sensor. (Which is the exact reason for buying this particular product from Namron.)

**Comment by prj84** [comment]
We have reaced out to developer to see if this can be fixed very soon.

**Comment by prj84** [comment]
Manufactorer has started the work on this, so will be included in the next full release of the app

**Comment by tj75** [comment]
> Manufactorer has started the work on this, so will be included in the next full release of the app

That is great news, thank you!

**Comment by prj84** [comment]
Added in 2.2.90 that will be released soon

**Comment by hengelsc** [comment]
Great if you also can create regulator mode for 4512744/45 - Z-Wave Thermostat touch. I have several of these and need regulator mode of some of them.

**Comment by prj84** [comment]
> Great if you also can create regulator mode for 4512744/45 - Z-Wave Thermostat touch. I have several of these and need regulator mode of some of them.

I'm afraid that is not possible due to 744/745 does not have the regulator mode feature.

**Comment by hengelsc** [comment]
Hi,I also have the new Zigbee touch 4512752. Are there any plans for creating cards for regulator mode for this thermostat? My understanding is that this thermostat also may function as a regulator.Please advise.Med vennlig hilsen,Henrik K. EngelschiønGjettumveien 8, N-1346 Gjettum, ***@***.*** | Tel. +47 901 42 88828. feb. 2024 kl. 14:51 skrev Pål Hefre ***@***.***>:﻿

Great if you also can create regulator mode for 4512744/45 - Z-Wave Thermostat touch. I have several of these and need regulator mode of some of them.

I'm afraid that is not possible due to 744/745 does not have the regulator mode feature.
