### ISSUE TITLE
Namron app not working

### ISSUE THREAD

**Issue by Kris10anOls1** [NamronAS/Namron_Homey#195]
I have a Homey Bridge and my Namron app crashed over 72 hours ago. I have tried repowering both the router and the bridge two times now. I also tried to restart the bridge from the developer tool. Any suggestions to solve this issue?

**Comment by prj84** [comment]
We have reported the issue to Athom. We have not got any other reports in this issue at the moment. We have no solution to restart the app in cloud.

**Comment by prj84** [comment]
Got this from Athom support now. They are investigating the issue:

Hi Namron AS,

there is 1 single Homey for which the app fails to start. So it only affects one user. Nevertheless this is annoying for this user, so we will investigate why this is. It seems it can not start because it can not find the AppSettings for the app.

Regards, Athom

**Comment by lordradon** [comment]
The are several people this is happening to.
5d849c7d-69e9-4754-8ea1-0af64e74ed8a
