### ISSUE TITLE
Namron stoppes working om latest update

### ISSUE THREAD

**Issue by kaiangel777** [NamronAS/Namron_Homey#95]
All zwave remote controls and dimming switches stopped working on the updated version 2.2.69. No units are connected in homey app. Please fix immediately!!

**Comment by jon-boop** [comment]
I have the exact same problem. The Homey unit, and other devices are working fine, but not namron zwave units. I have restarted the unit several times. So now I have no lights in my home

**Comment by Roaldoien** [comment]
Same here

**Comment by prj84** [comment]
Hi!

There has been no changes on the app since 2. May 2023. when there was added new devices. 

We have put a update in the test inviroment today for you to test where we have reintroduced some old drivers we needed to remove when Athom had issues with their Homey Cloud:
https://homey.app/no-no/app/net.filllip-namron/Namron/test/
