### ISSUE TITLE
Namron devices not working after update 

### ISSUE THREAD

**Issue by jon-boop** [NamronAS/Namron_Homey#96]
I have many Namron devices, none are responding after the update yesterday. The Homey unit, and other devices are working fine, but not namron zwave units. I have restarted the unit several times. So now I have no lights in my home

Please solve the issue asap

**Comment by Roaldoien** [comment]
Same here

**Comment by prj84** [comment]
Hi!

There has been no changes on the app since 2. May 2023. when there was added new devices. 

We have put a update in the test inviroment today for you to test where we have reintroduced some old drivers we needed to remove when Athom had issues with their Homey Cloud
:
https://homey.app/no-no/app/net.filllip-namron/Namron/test/

**Comment by jon-boop** [comment]
I am unsure how to use this test environment. 
In my Homey feed it states " Namron has been automatically updated to version 2.2.69" and this is dated 17 days ago. Since this occurred none of my Namron zwave devices works. Were the error is I do not know.
I have now used candles for 17 days, luckily it is summertime otherwise I have had to replace all of these to actually have lights in my home.

**Comment by Roaldoien** [comment]
Same here but with zigbeeBest regardsRoald A. Øien, PhDProfessor | Special Education & Developmental PsychologyUiT – The Arctic University of NorwayUNN - University Hospital of Northern NorwayProfessor |  Child Study CenterYale University - School of MedicineSenior Associate Editor - Journal of Autism and Developmental Disorders@***@***.******@***.***: +47 930 99 994 / +47 776 44 34431. jul. 2023 kl. 11:50 skrev jon-boop ***@***.***>:﻿
I am unsure how to use this test environment.
In my Homey feed it states " Namron has been automatically updated to version 2.2.69" and this is dated 17 days ago. Since this occurred none of my Namron zwave devices works. Were the error is I do not know.
I have now used candles for 17 days, luckily it is summertime otherwise I have had to replace all of these to actually have lights in my home.

**Comment by prj84** [comment]
Just follow the link fron last post and install, then you have the test version of the app.MvhPål R. Hefre31. jul. 2023 kl. 11:50 skrev jon-boop ***@***.***>:﻿
I am unsure how to use this test environment.
In my Homey feed it states " Namron has been automatically updated to version 2.2.69" and this is dated 17 days ago. Since this occurred none of my Namron zwave devices works. Were the error is I do not know.
I have now used candles for 17 days, luckily it is summertime otherwise I have had to replace all of these to actually have lights in my home.

**Comment by Roaldoien** [comment]
Cant get it to woek with my zigbee dimmers or any namron profuct even after update. Fibaro zwave and heatit works but no namron device. Timeout 3000ms it saysBest regardsRoald A. Øien, PhDProfessor | Special Education & Developmental PsychologyUiT – The Arctic University of NorwayUNN - University Hospital of Northern NorwayProfessor |  Child Study CenterYale University - School of MedicineSenior Associate Editor - Journal of Autism and Developmental Disorders@***@***.******@***.***: +47 930 99 994 / +47 776 44 34431. jul. 2023 kl. 13:22 skrev Pål Hefre ***@***.***>:﻿
Just follow the link fron last post and install, then you have the test version of the app.MvhPål R. Hefre31. jul. 2023 kl. 11:50 skrev jon-boop ***@***.***>:﻿

I am unsure how to use this test environment.

In my Homey feed it states " Namron has been automatically updated to version 2.2.69" and this is dated 17 days ago. Since this occurred none of my Namron zwave devices works. Were the error is I do not know.

I have now used candles for 17 days, luckily it is summertime otherwise I have had to replace all of these to actually have lights in my home.

**Comment by jon-boop** [comment]
> Just follow the link fron last post and install, then you have the test version of the app.MvhPål R. Hefre

The test app is working. Now we can control all the devices as before.
Please let me know if you need more information

**Comment by Roaldoien** [comment]
Downloaded and installed namron .70 version.Does nor work with my added zigbee devices. Maybe they need to be added all over?Best regardsRoald A. Øien, PhDProfessor | Special Education & Developmental PsychologyUiT – The Arctic University of NorwayUNN - University Hospital of Northern NorwayProfessor |  Child Study CenterYale University - School of MedicineSenior Associate Editor - Journal of Autism and Developmental Disorders@***@***.******@***.***: +47 930 99 994 / +47 776 44 34431. jul. 2023 kl. 22:02 skrev jon-boop ***@***.***>:﻿

Just follow the link fron last post and install, then you have the test version of the app.MvhPål R. Hefre

The test app is working. Now we can control all the devices as before.
Please let me know if you need more information

**Comment by Roaldoien** [comment]
Confirmed: does not work with zigbee devices already added and version ending in .70.Best regardsRoald A. Øien, PhDProfessor | Special Education & Developmental PsychologyUiT – The Arctic University of NorwayUNN - University Hospital of Northern NorwayProfessor |  Child Study CenterYale University - School of MedicineSenior Associate Editor - Journal of Autism and Developmental Disorders@***@***.******@***.***: +47 930 99 994 / +47 776 44 34431. jul. 2023 kl. 22:02 skrev jon-boop ***@***.***>:﻿

Just follow the link fron last post and install, then you have the test version of the app.MvhPål R. Hefre

The test app is working. Now we can control all the devices as before.
Please let me know if you need more information

**Comment by prj84** [comment]
@Roaldoien - Do you have sny other zigbee devices working? Fibaro and Heatit is Z-Wave. It is just to be shure that the problem is not dead zigbee chip on your Homey Pro

**Comment by Roaldoien** [comment]
Need to check that! Might be a good point. Best regardsRoald A. Øien, PhDProfessor | Special Education & Developmental PsychologyUiT – The Arctic University of NorwayUNN - University Hospital of Northern NorwayProfessor |  Child Study CenterYale University - School of MedicineSenior Associate Editor - Journal of Autism and Developmental Disorders@***@***.******@***.***: +47 930 99 994 / +47 776 44 34431. jul. 2023 kl. 22:27 skrev Pål Hefre ***@***.***>:﻿
@Roaldoien - Do you have sny other zigbee devices working? Fibaro and Heatit is Z-Wave. It is just to be shure that the problem is not dead zigbee chip on your Homey Pro

**Comment by cihlen** [comment]
I have the same problem since I upgraded to version 2.2.69 two weeks ago. I thought it might have something to do with zigbee but I just got the new Homey 2023 today and it's the same problem.
When I click the Namron unit I get the error App unavailable.

**Comment by jon-boop** [comment]
@prj84 I made the mistake of updating back to the offical app. That didn't work, but when I went back to the test app it didnt work as before. Now I have to go into each light on my app to adjust it, before I could just press the icon and it turned on and off. And my light switch dont work. I have to admit that proably didnt work on the test version earlier also. But it did work fine before any update. Can you please look into this?
